name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  docker-build:
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      -
      name: Checkout
      uses: actions/checkout@v2
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/simpleserever:latest
#    runs-on: ubuntu-latest
#    env:
#      DOCKER_IMAGE_NAME: simpleserver
#    steps:
#      - name: Check out source code
#        uses: actions/checkout@v1
#
#      - name: Build and push docker image
#        run: |
#          TAG=$(echo $GITHUB_REF | grep -o "[0-9][\.].*")
#          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/${DOCKER_IMAGE_NAME}:$TAG
#          echo "Docker image: ${DOCKER_IMAGE}"
#          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
#          docker build -t $DOCKER_IMAGE .
#          docker push $DOCKER_IMAGE
